services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: sm_sport
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  sm-sport:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sm-sport
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/sm_sport
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: qvN8s4oVjKjV3pK8XnNQqfT2bSvq4Urz7o9iDg1m6vE=
      JWT_EXPIRATION: 3600000

    ports:
      - "8080:8080"
